[phases.setup]
nixPkgs = ["nodejs_18"]

aptPkgs = ["python3", "make", "g++"]

[phases.install]
cmds = [
  "corepack enable",
  "corepack prepare yarn@1.22.21 --activate",
  "yarn --version",
  "yarn install --frozen-lockfile"
]

[phases.build]
cmds = ["CI=false NODE_OPTIONS=--openssl-legacy-provider yarn build"]
